name: A Day In The Life
favicon: null
layout_spectrum: 0.84464545478113
typography_spectrum: 0.05771750980056822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7473189465235919
  lightness: 0.6930989385582507
  saturation: 0.9453987888991833
  rhythmicContrast: 0.28267370350658894
purpose: []
