name: A Day In The Life
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73101
title: 'Testing out the Grid... '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e9f3'
    - '#142f66'
    - '#4390d6'
    - '#ed5830'
    - '#a29d5b'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
