name: A Day In The Life
favicon: null
layout_spectrum: 0.50719
typography_spectrum: 0.73101
title: 'Testing out the Grid... '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4f5f6f'
    - '#031112'
    - '#72b7f2'
    - '#c5d9f1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
