name: A Day In The Life
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73101
title: "Welcome to my collection of clutter.  I'm in the process of migrating a bunch of stuff so figured, why not let the Grid throw it all into one bucket. Feel free to leave comments or reach out with any questions"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e9f3'
    - '#142f66'
    - '#4390d6'
    - '#ed5830'
    - '#a29d5b'
  brandStrength: 0
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
