name: A Day In The Life
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: A test page for photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.708454909035936
  lightness: 0.6006906155962497
  saturation: 0.37730867811478674
  rhythmicContrast: 0.644893009448424
purpose: []
