name: A Day In The Life
favicon: null
layout_spectrum: 0.7303503728471696
typography_spectrum: 0.656514730071649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5998879361432046
  lightness: 0.8639868437312543
  saturation: 0.7314438982866704
  rhythmicContrast: 0.6622738614678383
purpose: []
