name: A Day In The Life
favicon: null
layout_spectrum: 0.026071672327816486
typography_spectrum: 0.4098351593129337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6583056214731187
  lightness: 0.13290457567200065
  saturation: 0.7393093577120453
  rhythmicContrast: 0.33153959456831217
purpose: []
